import React from "react";
import { AbsoluteFill, OffthreadVideo, Img, staticFile, useCurrentFrame, useVideoConfig, interpolate, spring } from "remotion";
import { DemoClip } from "./DemoClip.jsx";
import { typeScale } from "../theme.js";
import { bulletAppearSec } from "../lib/timing.js";

/**
 * The split layout — the house style for a vertical Short cut from a landscape
 * capture. The demo fills the top zone (a gentle pan window, since the zone is
 * still wider-than-source-shaped than a full 9:16 frame); below a brand-colored
 * seam sits a content slot that changes per scene:
 *
 *   presenter — the same character talking the scene's narration, screenshare
 *               style (clip generated by presenter.mjs, muted here; the clean
 *               narration track plays on the main timeline)
 *   image     — a still with a slow push, for product/logo beats
 *   bullets   — an animated list, for feature-list beats
 *   captions  — nothing rendered here; the karaoke captions center themselves
 *               in the zone (the default)
 *
 * The top ~11% of the bottom zone is reserved for the seam-anchored caption
 * band, so bottom content pads itself clear of it.
 */

export const SPLIT_DEFAULT_PCT = 0.55;

/**
 * The slot that will actually render, after graceful degrades: a presenter slot
 * without a clip (or with the presenter disabled) falls back to captions rather
 * than leaving a hole. DemoVideo uses the same resolution to place captions.
 */
export function resolveBottom(scene, presenterMode) {
  const bottom = scene.bottom || { kind: "captions" };
  if (bottom.kind === "presenter" && (presenterMode === "none" || !scene.presenterVideo)) {
    return { kind: "captions" };
  }
  return bottom;
}

const BottomPresenter = ({ scene, fps, startFromSec = 0 }) => (
  <OffthreadVideo
    src={staticFile(scene.presenterVideo)}
    startFrom={Math.round(startFromSec * fps)}
    // Animated to this scene's narration, which the main timeline already plays.
    muted
    style={{
      width: "100%", height: "100%", objectFit: "cover",
      // A portrait clip cover-cropped into the squat zone keeps a mid-height
      // band; anchor it where avatar portraits put the face.
      objectPosition: scene.presenterFocusY ?? "50% 30%",
    }}
  />
);

const BottomImage = ({ bottom, durationInFrames }) => {
  const frame = useCurrentFrame();
  const scale = interpolate(frame, [0, durationInFrames], [1, 1.06], { extrapolateRight: "clamp" });
  return (
    <Img
      src={staticFile(bottom.image)}
      style={{
        width: "100%", height: "100%", objectFit: "cover",
        transform: `scale(${scale})`,
        transformOrigin: "50% 40%",
      }}
    />
  );
};

const BottomBullets = ({ bottom, scene, theme, fps, width, height, zoneH }) => {
  const frame = useCurrentFrame();
  const s = typeScale(width, height);
  const items = bottom.bullets || [];
  const durationSec = scene.durationSec || 6;

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        gap: Math.round(34 * s),
        // Clear the seam caption band; kept even with captions off, as breathing room.
        padding: `${Math.round(height * 0.11)}px 7% ${Math.round(zoneH * 0.06)}px`,
      }}
    >
      {items.map((b, i) => {
        const appearSec = bulletAppearSec(b, i, items.length, durationSec);
        const enter = spring({
          frame: frame - Math.round(appearSec * fps),
          fps,
          config: { damping: 200 },
          durationInFrames: Math.round(fps * 0.45),
        });
        return (
          <div
            key={i}
            style={{
              display: "flex",
              alignItems: "flex-start",
              gap: Math.round(20 * s),
              opacity: enter,
              transform: `translateX(${interpolate(enter, [0, 1], [-24, 0])}px)`,
            }}
          >
            <div
              style={{
                flexShrink: 0,
                width: Math.round(16 * s),
                height: Math.round(16 * s),
                marginTop: Math.round(16 * s),
                borderRadius: Math.round(5 * s),
                background: theme.primary,
              }}
            />
            <div style={{ font: `700 ${Math.round(42 * s)}px/1.3 ${theme.font}`, color: theme.text }}>
              {b.text}
            </div>
          </div>
        );
      })}
    </div>
  );
};

// The seam-bordered bottom band and its content slot. Exported so BeatScene's
// anchored layout can mount it ONCE for a whole scene (continuous presenter)
// while the top pane hard-cuts per beat.
export const BottomZone = ({ scene, bottom, theme, fps, width, height, topH, presenterStartSec = 0, durationInFrames }) => {
  const s = typeScale(width, height);
  return (
    <div
      style={{
        position: "absolute",
        top: topH,
        left: 0,
        width,
        height: height - topH,
        overflow: "hidden",
        background: theme.bg,
        borderTop: `${Math.max(2, Math.round(4 * s))}px solid ${theme.primary}`,
        boxShadow: "0 -12px 30px rgba(0,0,0,.35)",
      }}
    >
      {bottom.kind === "presenter" ? (
        <BottomPresenter scene={scene} fps={fps} startFromSec={presenterStartSec} />
      ) : bottom.kind === "image" ? (
        <BottomImage bottom={bottom} durationInFrames={durationInFrames} />
      ) : bottom.kind === "bullets" ? (
        <BottomBullets
          bottom={bottom} scene={scene} theme={theme} fps={fps}
          width={width} height={height} zoneH={height - topH}
        />
      ) : null /* captions render from the caption layer, centered in this zone */}
    </div>
  );
};

// presenterStartSec/demoStartSec are set by beat windows so both zones' clips
// (and the demo's event clock) stay aligned with the continuous narration.
export const SplitScene = ({ scene, theme, fps, presenterMode, presenterStartSec = 0, demoStartSec = 0 }) => {
  const { width, height, durationInFrames } = useVideoConfig();
  const pct = scene.splitPct ?? SPLIT_DEFAULT_PCT;
  const topH = Math.round(height * pct);
  const bottom = resolveBottom(scene, presenterMode);

  return (
    <AbsoluteFill style={{ backgroundColor: theme.bg }}>
      <div style={{ position: "absolute", top: 0, left: 0, width, height: topH, overflow: "hidden" }}>
        <DemoClip
          scene={{ ...scene, framing: scene.topFraming }}
          theme={theme}
          fps={fps}
          boxW={width}
          boxH={topH}
          startFromSec={demoStartSec}
        />
      </div>

      <BottomZone
        scene={scene} bottom={bottom} theme={theme} fps={fps}
        width={width} height={height} topH={topH}
        presenterStartSec={presenterStartSec} durationInFrames={durationInFrames}
      />
    </AbsoluteFill>
  );
};
