#!/usr/bin/env node
/**
 * End-to-end assembly test that costs nothing.
 *
 *   node scripts/selftest.mjs [--keep] [--dir <path>]
 *
 * Builds a complete demo project whose media is synthesised locally with ffmpeg
 * (`lavfi` test patterns and sine tones) instead of generated by fal, then runs the
 * real build-props and Remotion render over it.
 *
 * This exercises every part of the pipeline that does not need an API key or screen
 * permissions: the manifest, validation, duration reconciliation, the event-driven
 * zoom, captions, transitions, audio layout and the renderer. Run it after changing
 * anything in remotion-template/ — a broken component otherwise only shows up at
 * the end of a real run, after the expensive parts have already been paid for.
 */
import path from "node:path";
import os from "node:os";
import { mkdir, writeFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import { parseArgs, boolArg } from "./lib/args.mjs";
import { ffmpeg, probe } from "./lib/ff.mjs";
import * as manifest from "./lib/manifest.mjs";
import { report, info, warn, main, fmtDuration } from "./lib/log.mjs";

const PLUGIN_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/** A silent colour-bars clip standing in for a screen recording or generated shot. */
async function fakeClip(file, { seconds, w = 1280, h = 720, pattern = "testsrc2" }) {
  await ffmpeg([
    "-f", "lavfi", "-i", `${pattern}=size=${w}x${h}:rate=30:duration=${seconds}`,
    "-t", String(seconds),
    "-c:v", "libx264", "-preset", "ultrafast", "-pix_fmt", "yuv420p",
    file,
  ]);
}

/** A tone standing in for narration, so audio layout and ducking are exercised. */
async function fakeAudio(file, { seconds, freq = 320 }) {
  await ffmpeg([
    "-f", "lavfi", "-i", `sine=frequency=${freq}:duration=${seconds}`,
    "-t", String(seconds),
    "-c:a", "libmp3lame", "-q:a", "6",
    file,
  ]);
}

function run(cmd, args, cwd) {
  return new Promise((resolve, reject) => {
    const p = spawn(cmd, args, { cwd, stdio: "inherit" });
    p.on("error", reject);
    p.on("close", (code) => (code === 0 ? resolve() : reject(new Error(`${cmd} exited ${code}`))));
  });
}

await main(async () => {
  const args = parseArgs(process.argv.slice(2));
  const dir = path.resolve(args.dir || path.join(os.tmpdir(), `demoday-selftest-${Date.now()}`));
  const keep = boolArg(args.keep, false);

  info(`  project: ${dir}`);
  for (const sub of ["clips", "audio", "assets", "out"]) {
    await mkdir(path.join(dir, sub), { recursive: true });
  }

  // ---- synthetic media -----------------------------------------------------
  info("  synthesising media with ffmpeg (no API calls)…");
  await Promise.all([
    fakeClip(path.join(dir, "clips", "intro.mp4"), { seconds: 4, pattern: "smptebars" }),
    fakeClip(path.join(dir, "clips", "demo.mp4"), { seconds: 9 }),
    fakeClip(path.join(dir, "clips", "broll.mp4"), { seconds: 5, pattern: "rgbtestsrc" }),
    fakeClip(path.join(dir, "clips", "cli.mp4"), { seconds: 6, pattern: "testsrc" }),
    fakeAudio(path.join(dir, "audio", "intro.mp3"), { seconds: 4, freq: 300 }),
    fakeAudio(path.join(dir, "audio", "demo.mp3"), { seconds: 9, freq: 380 }),
    fakeAudio(path.join(dir, "audio", "broll.mp3"), { seconds: 5, freq: 260 }),
    fakeAudio(path.join(dir, "audio", "cli.mp3"), { seconds: 6, freq: 440 }),
  ]);

  // A capture event log, so zoom-to-click and callout anchoring are exercised.
  await writeFile(
    path.join(dir, "clips", "demo.events.json"),
    JSON.stringify({
      version: 1, clip: "demo.mp4", viewport: { width: 1280, height: 720 }, durationSec: 9,
      events: [
        { type: "click", atMs: 1800, x: 300, y: 140, label: "first click" },
        { type: "click", atMs: 5200, x: 980, y: 430, label: "second click" },
        { type: "highlight", atMs: 7000, x: 640, y: 300, label: "result" },
      ],
    }, null, 2)
  );

  // A CLI event log: no click events (terminals rarely click), retimed like a
  // real cli-perform take — proves a click-less scene renders flat, not crashing.
  await writeFile(
    path.join(dir, "clips", "cli.events.json"),
    JSON.stringify({
      version: 1, clip: "cli.mp4", viewport: { width: 1280, height: 720 }, durationSec: 6,
      retime: { rawSec: 8.6, factor: 0.7, clamped: false },
      events: [
        { type: "type", atMs: 700, text: "claude", label: "launch claude" },
        { type: "waitStable", atMs: 4200, waitedMs: 5000, timedOut: false, label: "claude finishes" },
      ],
    }, null, 2)
  );

  // Word timings, so the caption component is exercised.
  await writeFile(
    path.join(dir, "audio", "demo.words.json"),
    JSON.stringify({
      text: "Create a project and it appears instantly in your dashboard.",
      timestamps: "Create a project and it appears instantly in your dashboard."
        .split(" ")
        .map((word, i) => ({ text: word, startSec: 0.4 + i * 0.75, endSec: 0.4 + i * 0.75 + 0.6 })),
    }, null, 2)
  );

  // ---- the manifest --------------------------------------------------------
  const m = manifest.blankManifest({ slug: "selftest", name: "Selftest" });
  m.format = { width: 1280, height: 720, fps: 30 };
  m.presenter.mode = "hybrid";
  m.captions = { enabled: true, style: "clean" };
  m.timeline = [
    {
      id: "title", kind: "card", durationSec: 2.5,
      title: "Selftest", subtitle: "Proving the pipeline with zero spend",
    },
    {
      id: "intro", kind: "presenter", durationSec: 4,
      narration: "This stands in for the presenter.",
      audio: "audio/intro.mp3", video: "clips/intro.mp4",
      lowerThird: { title: "Alex Rivera", subtitle: "Product Lead" },
    },
    {
      id: "demo", kind: "demo", target: "web", durationSec: 9,
      narration: "Create a project and it appears instantly in your dashboard.",
      audio: "audio/demo.mp3", words: "audio/demo.words.json",
      video: "clips/demo.mp4", events: "clips/demo.events.json",
      actions: "actions/demo.json",
      overlays: [{ type: "callout", atSec: 1.9, text: "One click", anchor: "lastClick" }],
    },
    {
      id: "cli", kind: "demo", target: "cli", durationSec: 6, cwd: ".",
      narration: "One slash command and the plugin does the rest.",
      audio: "audio/cli.mp3",
      video: "clips/cli.mp4", events: "clips/cli.events.json",
    },
    {
      id: "broll", kind: "broll", durationSec: 5,
      prompt: "a developer at a desk", narration: "Teams ship faster.",
      audio: "audio/broll.mp3", video: "clips/broll.mp4",
    },
    { id: "outro", kind: "card", durationSec: 3, title: "Thanks for watching", cta: "acme.dev/start" },
  ];
  m.transitions = [
    { after: "title", type: "fade", ms: 400 },
    { after: "intro", type: "wipe", ms: 500 },
    { after: "demo", type: "slide", ms: 400 },
    { after: "broll", type: "fade", ms: 400 },
  ];
  await manifest.save(dir, m);

  // ---- validation ----------------------------------------------------------
  const check = manifest.validate(m);
  if (!check.ok) throw new Error(`selftest manifest is invalid:\n  - ${check.errors.join("\n  - ")}`);
  info(`  manifest valid (${m.timeline.length} scenes)`);

  const expected =
    m.timeline.reduce((s, x) => s + x.durationSec, 0) -
    m.transitions.reduce((s, t) => s + t.ms / 1000, 0);

  // ---- render --------------------------------------------------------------
  info("  rendering…");
  const out = path.join(dir, "out", "selftest.mp4");
  await run("node", [path.join(PLUGIN_ROOT, "scripts", "render", "render.mjs"), "--project", dir, "--out", out]);

  if (!existsSync(out)) throw new Error("render produced no file");
  const meta = await probe(out);
  const drift = Math.abs((meta.duration || 0) - expected);

  const ok = drift <= 0.5 && meta.width === 1280 && meta.height === 720;
  if (!ok) {
    warn(`expected ${fmtDuration(expected)} at 1280x720, got ${fmtDuration(meta.duration)} at ${meta.width}x${meta.height}`);
  }

  if (!keep) {
    // Keep the rendered video but drop the scaffolded node_modules, which is large.
    await rm(path.join(dir, "remotion", "node_modules"), { recursive: true, force: true }).catch(() => {});
  }

  report(
    ok
      ? `  PASS — rendered ${fmtDuration(meta.duration)} at ${meta.width}x${meta.height}\n  ${out}`
      : `  FAIL — see warnings above`,
    {
      ok,
      video: out,
      expectedSec: expected,
      actualSec: meta.duration,
      driftSec: drift,
      width: meta.width,
      height: meta.height,
      project: dir,
    }
  );
  if (!ok) process.exit(1);
});
